<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-08T10:47:44Z" name="Default suite" finished-at="2021-02-08T10:48:35Z" duration-ms="51267">
    <groups>
    </groups>
    <test started-at="2021-02-08T10:47:44Z" name="Default test" finished-at="2021-02-08T10:48:35Z" duration-ms="51267">
      <class name="com.qa.tests.C7_001_DefaultingPlans">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.tests.C7_001_DefaultingPlans@1df8b5b8]" started-at="2021-02-08T10:47:44Z" name="setup" finished-at="2021-02-08T10:47:57Z" duration-ms="13203" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test1_MasterListPage_Loaded()[pri:0, instance:com.qa.tests.C7_001_DefaultingPlans@1df8b5b8]" started-at="2021-02-08T10:47:57Z" name="test1_MasterListPage_Loaded" finished-at="2021-02-08T10:48:07Z" duration-ms="10127" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1_MasterListPage_Loaded -->
        <test-method signature="test01_CreditDefaulting()[pri:1, instance:com.qa.tests.C7_001_DefaultingPlans@1df8b5b8]" started-at="2021-02-08T10:48:07Z" name="test01_CreditDefaulting" finished-at="2021-02-08T10:48:22Z" depends-on-methods="com.qa.tests.C7_001_DefaultingPlans.test1_MasterListPage_Loaded" duration-ms="14554" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test01_CreditDefaulting -->
        <test-method signature="test02_CreditDefaulting()[pri:2, instance:com.qa.tests.C7_001_DefaultingPlans@1df8b5b8]" started-at="2021-02-08T10:48:22Z" name="test02_CreditDefaulting" finished-at="2021-02-08T10:48:35Z" depends-on-methods="com.qa.tests.C7_001_DefaultingPlans.test01_CreditDefaulting" duration-ms="13365" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-1] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-1] but found [1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.qa.tests.C7_001_DefaultingPlans.test02_CreditDefaulting(C7_001_DefaultingPlans.java:204)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test02_CreditDefaulting -->
      </class> <!-- com.qa.tests.C7_001_DefaultingPlans -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
